import type { Metadata } from "next";
import "./css/globals.css";
import { Manrope } from "next/font/google"
import 'aos/dist/aos.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const manrope = Manrope({ weight: ["500", "600", "700"], subsets: ["latin"], variable: "--font-tertiary" })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${manrope.variable}`}>
        {children}
      </body>
    </html>
  );
}
